inputs:
- branch: master
  path: .tekton
  type: git
  service: ${githubconsolidated00}
- branch: master
  path: .tekton
  type: git
  service: ${githubconsolidated02}
- branch: master
  path: .tekton-listener
  type: git
  service: ${githubconsolidated02}
private_worker: ${private_worker01}
triggers:
- eventListener: listener
  name: Manual Trigger
  type: manual
properties:
- name: secureproperty
  type: SECURE
  value: ""
- name: textareaproperty
  type: textarea
  value: Text Area Property Value
- name: textproperty
  type: text
  value: Text Property Value
