stages:
- inputs:
  - branch: master
    dir_name: null
    type: git
    service: service01
  jobs:
  - artifact_dir: ""
    build_type: shell
    curatedDockerImage: default
    name: Build1
    script: |-
      #!/bin/bash
      ls -l
      env | sort | grep property
    type: builder
  name: Stage1
  permission:
    execute: TOOLCHAIN_ADMINS
  properties:
  - name: stage1_text_property
    type: text
    value: textvalue
  - name: stage1_secure_property
    type: secure
  triggers:
  - events: '{"push":true,"pull_request":false,"pull_request_closed":false}'
    type: git
- inputs:
  - branch: master
    dir_name: null
    type: git
    service: service02
  jobs:
  - artifact_dir: ""
    build_type: shell
    curatedDockerImage: default
    name: Build2
    script: |-
      #!/bin/bash
      ls -l
      env | sort | grep property
    type: builder
  name: Stage2
  permission:
    execute: TOOLCHAIN_ADMINS
  properties:
  - name: stage2_text_property
    type: text
    value: textvalue
  - name: stage2_secure_property
    type: secure
  triggers:
  - type: stage
properties:
- name: pipeline_text_property
  type: text
  value: textvalue
- name: pipeline_secure_property
  type: secure
