inputs:
- branch: master
  path: .tekton
  type: git
  service: ${service02}
- branch: master
  path: .tekton-listener
  type: git
  service: ${service02}
- branch: master
  path: .tekton
  type: git
  service: ${service01}
triggers:
- eventListener: listener
  name: Manual Trigger
  type: manual
properties:
- name: tekton_text_property
  type: text
  value: textvalue
