services:
  build:
    parameters:
      configuration:
        content:
          $text: pipeline_build.yml
        env:
          repo: repo
        execute: false
      label: simple-tekton-toolchain-20200119131027988
      name: simple-tekton-toolchain-20200119131027988
      services:
      - repo
      type: tekton
      ui_pipeline: true
    service_id: pipeline
  repo:
    parameters:
      api_root_url: https://api.github.com
      authorized: github
      custom_host: ""
      enable_traceability: true
      extra_capabilities:
      - capability_id: git.issues
        dashboard_url: https://github.com/jauninb/hello-tekton/issues
        display_name: Issues
        enabled: false
        label: hello-tekton
        readme: false
        tags:
        - think
        - code
      git_id: github
      has_issues: false
      label: hello-tekton
      legal: false
      legal_label: ""
      namespace_table: ""
      owner_id: jauninb
      private_repo: false
      repo_name: hello-tekton
      repo_url: https://github.com/jauninb/hello-tekton.git
      source_repo_url: https://github.com/open-toolchain/hello-tekton
      token_url: https://otc-github-consolidated-broker.us-south.devops.cloud.ibm.com/github/token?git_id=github
      type: link
    service_id: githubpublic
  webide:
    parameters:
      container_url: ""
      dashboard_url: /devops/code/edit/edit.html#,toolchain=46fb2218-3b46-4d38-9a55-767da5935b6f
      toolchain_id: 46fb2218-3b46-4d38-9a55-767da5935b6f
    service_id: orion
template:
  description: simple-tekton-toolchain-20200119131027988
  name: Develop a Kubernetes app
  required:
  - repo
toolchain:
  name: simple-tekton-toolchain-20200119131027988
version: 2
